# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-26 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20181126_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictures',
            new_name='picture',
        ),
    ]
